# Stage 1: Base image
FROM node:20-alpine AS base
RUN npm install -g pnpm

# Stage 2: Builder Stage
FROM base AS builder
WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.base.json ./

COPY api/package.json ./api/

RUN pnpm install --filter api...

COPY api ./api/

WORKDIR /app/api
RUN pnpm exec prisma generate
RUN pnpm run build

# Stage 3: Runner Stage
FROM base AS runner
WORKDIR /app/api

ENV NODE_ENV=production

COPY --from=builder /app/api/dist ./dist
COPY --from=builder /app/api/package.json ./

RUN pnpm install --prod

EXPOSE 5000

RUN addgroup -g 1001 appgroup && \
    adduser -D -u 1001 -G appgroup appuser && \
    chown -R appuser:appgroup /app
USER appuser

CMD ["node", "dist/main.cjs"]
